return {
    -- TEMPLATES FOR COPY/PASTE
    -- [""] = {result = "", amount = 1, input = {[""] = 1}},

    ["ms-chemical-card-battery"] = {result = "battery", amount = 1, input = {["copper-plate"] = 1, ["iron-plate"] = 1, ["ms-digital-sulfuric-acid"] = 20}},
    ["ms-chemical-card-explosives"] = {result = "explosives", amount = 2, input = {["coal"] = 1, ["sulfur"] = 1, ["ms-digital-water"] = 10}},
    ["ms-chemical-card-plastic-bar"] = {result = "plastic-bar", amount = 1, input = {["coal"] = 1, ["ms-digital-petroleum-gas"] = 20}},
    ["ms-chemical-card-solid-fuel-1"] = {result = "solid-fuel", amount = 1, input = {["ms-digital-petroleum-gas"] = 20}},
    ["ms-chemical-card-solid-fuel-2"] = {result = "solid-fuel", amount = 1, input = {["ms-digital-light-oil"] = 10}},
    ["ms-chemical-card-solid-fuel-3"] = {result = "solid-fuel", amount = 1, input = {["ms-digital-heavy-oil"] = 20}},
    ["ms-chemical-card-sulfur"] = {result = "sulfur", amount = 2, input = {["ms-digital-petroleum-gas"] = 30, ["ms-digital-water"] = 30}},

    ["ms-crafting-card-advanced-circuit"] = {result = "advanced-circuit", amount = 1, input = {["copper-cable"] = 4, ["electronic-circuit"] = 2, ["plastic-bar"] = 1}},
    ["ms-crafting-card-assembling-machine-1"] = {result = "assembling-machine-1", amount = 1, input = {["electronic-circuit"] = 3, ["iron-gear-wheel"] = 5, ["iron-plate"] = 9}},
    ["ms-crafting-card-assembling-machine-2"] = {result = "assembling-machine-2", amount = 1, input = {["assembling-machine-1"] = 1, ["electronic-circuit"] = 3, ["iron-gear-wheel"] = 5, ["steel-plate"] = 2}},
    ["ms-crafting-card-assembling-machine-3"] = {result = "assembling-machine-3", amount = 1, input = {["assembling-machine-2"] = 2, ["speed-module"] = 4}},
    ["ms-crafting-card-automation-science-pack"] = {result = "automation-science-pack", amount = 1, input = {["copper-plate"] = 1, ["iron-gear-wheel"] = 1}},
    ["ms-crafting-card-chemical-science-pack"] = {result = "chemical-science-pack", amount = 1, input = {["advanced-circuit"] = 3, ["engine-unit"] = 2, ["sulfur"] = 1}},
    ["ms-crafting-card-copper-cable"] = {result = "copper-cable", amount = 2, input = {["copper-plate"] = 1}},
    ["ms-crafting-card-electric-engine-unit"] = {result = "electric-engine-unit", amount = 1, input = {["electronic-circuit"] = 2, ["engine-unit"] = 1, ["ms-digital-lubricant"] = 15}},
    ["ms-crafting-card-electric-furnace"] = {result = "electric-furnace", amount = 1, input = {["advanced-circuit"] = 5, ["steel-plate"] = 10, ["stone-brick"] = 10}},
    ["ms-crafting-card-electronic-circuit"] = {result = "electronic-circuit", amount = 1, input = {["copper-cable"] = 3, ["iron-plate"] = 1}},
    ["ms-crafting-card-engine-unit"] = {result = "engine-unit", amount = 1, input = {["iron-gear-wheel"] = 1, ["pipe"] = 2, ["steel-plate"] = 1}},
    ["ms-crafting-card-express-splitter"] = {result = "express-splitter", amount = 1, input = {["advanced-circuit"] = 10, ["fast-splitter"] = 1, ["iron-gear-wheel"] = 10, ["ms-digital-lubricant"] = 80}},
    ["ms-crafting-card-express-transport-belt"] = {result = "express-transport-belt", amount = 1, input = {["fast-transport-belt"] = 1, ["iron-gear-wheel"] = 10, ["ms-digital-lubricant"] = 20}},
    ["ms-crafting-card-express-underground-belt"] = {result = "express-underground-belt", amount = 2, input = {["fast-underground-belt"] = 2, ["iron-gear-wheel"] = 80, ["ms-digital-lubricant"] = 40}},
    ["ms-crafting-card-fast-inserter"] = {result = "fast-inserter", amount = 1, input = {["electronic-circuit"] = 2, ["inserter"] = 1, ["iron-plate"] = 2}},
    ["ms-crafting-card-fast-splitter"] = {result = "fast-splitter", amount = 1, input = {["electronic-circuit"] = 10, ["iron-gear-wheel"] = 10, ["splitter"] = 1}},
    ["ms-crafting-card-fast-transport-belt"] = {result = "fast-transport-belt", amount = 1, input = {["transport-belt"] = 1, ["iron-gear-wheel"] = 5}},
    ["ms-crafting-card-fast-underground-belt"] = {result = "fast-underground-belt", amount = 2, input = {["underground-belt"] = 2, ["iron-gear-wheel"] = 40}},
    ["ms-crafting-card-filter-inserter"] = {result = "filter-inserter", amount = 1, input = {["electronic-circuit"] = 4, ["fast-inserter"] = 1}},
    ["ms-crafting-card-firearm-magazine"] = {result = "firearm-magazine", amount = 1, input = {["iron-plate"] = 4}},
    ["ms-crafting-card-flying-robot-frame"] = {result = "flying-robot-frame", amount = 1, input = {["battery"] = 2, ["electric-engine-unit"] = 1, ["electronic-circuit"] = 3, ["steel-plate"] = 1}},
    ["ms-crafting-card-grenade"] = {result = "grenade", amount = 1, input = {["coal"] = 10, ["iron-plate"] = 5}},
    ["ms-crafting-card-inserter"] = {result = "inserter", amount = 1, input = {["electronic-circuit"] = 1, ["iron-gear-wheel"] = 1, ["iron-plate"] = 1}},
    ["ms-crafting-card-iron-chest"] = {result = "iron-chest", amount = 1, input = {["iron-plate"] = 8}},
    ["ms-crafting-card-iron-gear-wheel"] = {result = "iron-gear-wheel", amount = 1, input = {["iron-plate"] = 2}},
    ["ms-crafting-card-iron-stick"] = {result = "iron-stick", amount = 2, input = {["iron-plate"] = 1}},
    ["ms-crafting-card-logistic-science-pack"] = {result = "logistic-science-pack", amount = 1, input = {["inserter"] = 1, ["transport-belt"] = 1}},
    ["ms-crafting-card-long-handed-inserter"] = {result = "long-handed-inserter", amount = 1, input = {["inserter"] = 1, ["iron-gear-wheel"] = 1, ["iron-plate"] = 1}},
    ["ms-crafting-card-low-density-structure"] = {result = "low-density-structure", amount = 1, input = {["copper-plate"] = 20, ["plastic-bar"] = 5, ["steel-plate"] = 2}},
    ["ms-crafting-card-medium-electric-pole"] = {result = "medium-electric-pole", amount = 1, input = {["copper-plate"] = 2, ["iron-stick"] = 4, ["steel-plate"] = 2}},
    ["ms-crafting-card-military-science-pack"] = {result = "military-science-pack", amount = 1, input = {["grenade"] = 1, ["piercing-rounds-magazine"] = 1, ["stone-wall"] = 2}},
    ["ms-crafting-card-piercing-rounds-magazine"] = {result = "piercing-rounds-magazine", amount = 1, input = {["copper-plate"] = 5, ["firearm-magazine"] = 1, ["steel-plate"] = 1}},
    ["ms-crafting-card-pipe"] = {result = "pipe", amount = 1, input = {["iron-plate"] = 1}},
    ["ms-crafting-card-pipe-to-ground"] = {result = "pipe-to-ground", amount = 2, input = {["pipe"] = 10, ["iron-plate"] = 5}},
    ["ms-crafting-card-processing-unit"] = {result = "processing-unit", amount = 1, input = {["advanced-circuit"] = 2, ["electronic-circuit"] = 20, ["ms-digital-sulfuric-acid"] = 5}},
    ["ms-crafting-card-production-science-pack"] = { result = "production-science-pack", amount = 3, input = {["electric-furnace"] = 1, ["productivity-module"] = 1, ["rail"] = 30}},
    ["ms-crafting-card-productivity-module"] = {result = "productivity-module", amount = 1, input = {["electronic-circuit"] = 5, ["advanced-circuit"] = 5}},
    ["ms-crafting-card-rail"] = {result = "rail", amount = 1, input = {["iron-stick"] = 1, ["steel-plate"] = 1, ["stone"] = 1}},
    ["ms-crafting-card-rocket-control-unit"] = {result = "rocket-control-unit", amount = 1, input = {["processing-unit"] = 1, ["speed-module"] = 1}},
    ["ms-crafting-card-rocket-fuel"] = {result = "rocket-fuel", amount = 1, input = {["ms-digital-light-oil"] = 10, ["solid-fuel"] = 10}},
    ["ms-crafting-card-small-lamp"] = {result = "small-lamp", amount = 1, input = {["copper-cable"] = 3, ["electronic-circuit"] = 1, ["iron-plate"] = 1}},
    ["ms-crafting-card-speed-module"] = {result = "speed-module", amount = 1, input = {["electronic-circuit"] = 5, ["advanced-circuit"] = 5}},
    ["ms-crafting-card-splitter"] = {result = "splitter", amount = 1, input = {["electronic-circuit"] = 5, ["iron-plate"] = 5, ["transport-belt"] = 4}},
    ["ms-crafting-card-stack-inserter"] = {result = "stack-inserter", amount = 1, input = {["advanced-circuit"] = 1, ["electronic-circuit"] = 15, ["fast-inserter"] = 1, ["iron-gear-wheel"] = 15}},
    ["ms-crafting-card-steel-chest"] = {result = "steel-chest", amount = 1, input = {["steel-plate"] = 8}},
    ["ms-crafting-card-stone-wall"] = {result = "stone-wall", amount = 1, input = {["stone-brick"] = 5}},
    ["ms-crafting-card-transport-belt"] = {result = "transport-belt", amount = 2, input = {["iron-gear-wheel"] = 1, ["iron-plate"] = 1}},
    ["ms-crafting-card-underground-belt"] = {result = "underground-belt", amount = 2, input = {["iron-plate"] = 10, ["transport-belt"] = 5}},
    ["ms-crafting-card-utility-science-pack"] = {result = "utility-science-pack", amount = 3, input = {["flying-robot-frame"] = 1, ["low-density-structure"] = 3, ["processing-unit"] = 2}},

    ["ms-smelting-card-copper-plate"] = {result = "copper-plate", amount = 1, input = {["copper-ore"] = 1}},
    ["ms-smelting-card-iron-plate"] = {result = "iron-plate", amount = 1, input = {["iron-ore"] = 1}},
    ["ms-smelting-card-steel-plate"] = {result = "steel-plate", amount = 1, input = {["iron-plate"] = 5}},
    ["ms-smelting-card-stone-brick"] = {result = "stone-brick", amount = 1, input = {["stone"] = 2}}
}